%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clearvars -global
clear_persistent_variables(fileparts(which('dynare')), false)
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info
options_ = [];
M_.fname = 'inflation_network_realwage_fix';
M_.dynare_version = '7.0';
oo_.dynare_version = '7.0';
options_.dynare_version = '7.0';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(1,1);
M_.exo_names_tex = cell(1,1);
M_.exo_names_long = cell(1,1);
M_.exo_names(1) = {'totsh'};
M_.exo_names_tex(1) = {'totsh'};
M_.exo_names_long(1) = {'totsh'};
M_.endo_names = cell(13,1);
M_.endo_names_tex = cell(13,1);
M_.endo_names_long = cell(13,1);
M_.endo_names(1) = {'infl'};
M_.endo_names_tex(1) = {'infl'};
M_.endo_names_long(1) = {'infl'};
M_.endo_names(2) = {'cpi'};
M_.endo_names_tex(2) = {'cpi'};
M_.endo_names_long(2) = {'cpi'};
M_.endo_names(3) = {'resetprice_D'};
M_.endo_names_tex(3) = {'resetprice\_D'};
M_.endo_names_long(3) = {'resetprice_D'};
M_.endo_names(4) = {'gdp'};
M_.endo_names_tex(4) = {'gdp'};
M_.endo_names_long(4) = {'gdp'};
M_.endo_names(5) = {'employ'};
M_.endo_names_tex(5) = {'employ'};
M_.endo_names_long(5) = {'employ'};
M_.endo_names(6) = {'nomint'};
M_.endo_names_tex(6) = {'nomint'};
M_.endo_names_long(6) = {'nomint'};
M_.endo_names(7) = {'rwage'};
M_.endo_names_tex(7) = {'rwage'};
M_.endo_names_long(7) = {'rwage'};
M_.endo_names(8) = {'rmc_D'};
M_.endo_names_tex(8) = {'rmc\_D'};
M_.endo_names_long(8) = {'rmc_D'};
M_.endo_names(9) = {'nmc_D'};
M_.endo_names_tex(9) = {'nmc\_D'};
M_.endo_names_long(9) = {'nmc_D'};
M_.endo_names(10) = {'tot'};
M_.endo_names_tex(10) = {'tot'};
M_.endo_names_long(10) = {'tot'};
M_.endo_names(11) = {'cpi_U'};
M_.endo_names_tex(11) = {'cpi\_U'};
M_.endo_names_long(11) = {'cpi_U'};
M_.endo_names(12) = {'resetprice_U'};
M_.endo_names_tex(12) = {'resetprice\_U'};
M_.endo_names_long(12) = {'resetprice_U'};
M_.endo_names(13) = {'infl_U'};
M_.endo_names_tex(13) = {'infl\_U'};
M_.endo_names_long(13) = {'infl_U'};
M_.endo_partitions = struct();
M_.param_names = cell(15,1);
M_.param_names_tex = cell(15,1);
M_.param_names_long = cell(15,1);
M_.param_names(1) = {'alph'};
M_.param_names_tex(1) = {'alph'};
M_.param_names_long(1) = {'alph'};
M_.param_names(2) = {'bet'};
M_.param_names_tex(2) = {'bet'};
M_.param_names_long(2) = {'bet'};
M_.param_names(3) = {'theta_D'};
M_.param_names_tex(3) = {'theta\_D'};
M_.param_names_long(3) = {'theta_D'};
M_.param_names(4) = {'theta_U'};
M_.param_names_tex(4) = {'theta\_U'};
M_.param_names_long(4) = {'theta_U'};
M_.param_names(5) = {'alph_D'};
M_.param_names_tex(5) = {'alph\_D'};
M_.param_names_long(5) = {'alph_D'};
M_.param_names(6) = {'epsil'};
M_.param_names_tex(6) = {'epsil'};
M_.param_names_long(6) = {'epsil'};
M_.param_names(7) = {'Phi_DU'};
M_.param_names_tex(7) = {'Phi\_DU'};
M_.param_names_long(7) = {'Phi_DU'};
M_.param_names(8) = {'mf'};
M_.param_names_tex(8) = {'mf'};
M_.param_names_long(8) = {'mf'};
M_.param_names(9) = {'psi_w'};
M_.param_names_tex(9) = {'psi\_w'};
M_.param_names_long(9) = {'psi_w'};
M_.param_names(10) = {'intsub'};
M_.param_names_tex(10) = {'intsub'};
M_.param_names_long(10) = {'intsub'};
M_.param_names(11) = {'frisch'};
M_.param_names_tex(11) = {'frisch'};
M_.param_names_long(11) = {'frisch'};
M_.param_names(12) = {'phi'};
M_.param_names_tex(12) = {'phi'};
M_.param_names_long(12) = {'phi'};
M_.param_names(13) = {'chipi'};
M_.param_names_tex(13) = {'chipi'};
M_.param_names_long(13) = {'chipi'};
M_.param_names(14) = {'chiy'};
M_.param_names_tex(14) = {'chiy'};
M_.param_names_long(14) = {'chiy'};
M_.param_names(15) = {'rho'};
M_.param_names_tex(15) = {'rho'};
M_.param_names_long(15) = {'rho'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 1;
M_.endo_nbr = 13;
M_.param_nbr = 15;
M_.orig_endo_nbr = 13;
M_.aux_vars = [];
M_.heterogeneity_aggregates = {
};
M_.database = {};
M_.Sigma_e = zeros(1, 1);
M_.Correlation_matrix = eye(1, 1);
M_.Skew_e = zeros(0, 4);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = struct([]);
M_.surprise_shocks = struct([]);
M_.learnt_shocks = struct([]);
M_.learnt_endval = struct([]);
M_.shock_paths = struct([]);
M_.heteroskedastic_shocks.Qvalue_orig = struct([]);
M_.heteroskedastic_shocks.Qscale_orig = struct([]);
M_.matched_irfs = {};
M_.matched_irfs_weights = {};
M_.perfect_foresight_controlled_paths = struct([]);
options_.linear = true;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
options_.ramsey_policy = false;
options_.discretionary_policy = false;
M_.nonzero_hessian_eqs = [];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.eq_nbr = 13;
M_.ramsey_orig_eq_nbr = 0;
M_.ramsey_orig_endo_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 0 6 19;
 1 7 0;
 0 8 20;
 0 9 21;
 0 10 0;
 2 11 0;
 3 12 0;
 0 13 0;
 0 14 0;
 4 15 0;
 5 16 0;
 0 17 22;
 0 18 0;]';
M_.nstatic = 4;
M_.nfwrd   = 4;
M_.npred   = 5;
M_.nboth   = 0;
M_.nsfwrd   = 4;
M_.nspred   = 5;
M_.ndynamic   = 9;
M_.dynamic_tmp_nbr = [0; 0; 0; 0; ];
M_.equations_tags = {
  1 , 'name' , 'gdp' ;
  2 , 'name' , 'rmc_D' ;
  3 , 'name' , 'nmc_D' ;
  4 , 'name' , 'rwage' ;
  5 , 'name' , 'infl' ;
  6 , 'name' , 'infl_U' ;
  7 , 'name' , 'cpi' ;
  8 , 'name' , 'resetprice_D' ;
  9 , 'name' , 'cpi_U' ;
  10 , 'name' , 'resetprice_U' ;
  11 , 'name' , '11' ;
  12 , 'name' , 'nomint' ;
  13 , 'name' , 'tot' ;
};
M_.mapping.infl.eqidx = [5 11 12 ];
M_.mapping.cpi.eqidx = [2 3 5 7 10 ];
M_.mapping.resetprice_D.eqidx = [7 8 ];
M_.mapping.gdp.eqidx = [1 4 11 12 ];
M_.mapping.employ.eqidx = [1 4 ];
M_.mapping.nomint.eqidx = [11 12 ];
M_.mapping.rwage.eqidx = [2 4 10 ];
M_.mapping.rmc_D.eqidx = [2 3 ];
M_.mapping.nmc_D.eqidx = [3 8 ];
M_.mapping.tot.eqidx = [1 10 13 ];
M_.mapping.cpi_U.eqidx = [2 6 9 ];
M_.mapping.resetprice_U.eqidx = [9 10 ];
M_.mapping.infl_U.eqidx = [6 ];
M_.mapping.totsh.eqidx = [13 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.block_structure.time_recursive = false;
M_.block_structure.block(1).Simulation_Type = 1;
M_.block_structure.block(1).endo_nbr = 1;
M_.block_structure.block(1).mfs = 1;
M_.block_structure.block(1).equation = [ 13];
M_.block_structure.block(1).variable = [ 10];
M_.block_structure.block(1).is_linear = true;
M_.block_structure.block(1).bytecode_jacob_cols_to_sparse = [1 2 ];
M_.block_structure.block(2).Simulation_Type = 8;
M_.block_structure.block(2).endo_nbr = 11;
M_.block_structure.block(2).mfs = 11;
M_.block_structure.block(2).equation = [ 3 1 8 2 4 10 12 5 7 9 11];
M_.block_structure.block(2).variable = [ 8 5 9 11 7 2 6 1 3 12 4];
M_.block_structure.block(2).is_linear = true;
M_.block_structure.block(2).bytecode_jacob_cols_to_sparse = [4 5 6 7 12 13 14 15 16 17 18 19 20 21 22 30 31 32 33 ];
M_.block_structure.block(3).Simulation_Type = 1;
M_.block_structure.block(3).endo_nbr = 1;
M_.block_structure.block(3).mfs = 1;
M_.block_structure.block(3).equation = [ 6];
M_.block_structure.block(3).variable = [ 13];
M_.block_structure.block(3).is_linear = true;
M_.block_structure.block(3).bytecode_jacob_cols_to_sparse = [2 ];
M_.block_structure.block(1).g1_sparse_rowval = int32([]);
M_.block_structure.block(1).g1_sparse_colval = int32([]);
M_.block_structure.block(1).g1_sparse_colptr = int32([]);
M_.block_structure.block(2).g1_sparse_rowval = int32([10 5 8 9 7 1 4 2 5 1 3 4 10 4 5 6 1 4 6 8 9 7 11 7 8 3 9 6 10 2 5 7 11 11 3 6 11 ]);
M_.block_structure.block(2).g1_sparse_colval = int32([4 5 6 6 7 12 12 13 13 14 14 15 15 16 16 16 17 17 17 17 17 18 18 19 19 20 20 21 21 22 22 22 22 30 31 32 33 ]);
M_.block_structure.block(2).g1_sparse_colptr = int32([1 1 1 1 2 3 5 6 6 6 6 6 8 10 12 14 17 22 24 26 28 30 34 34 34 34 34 34 34 34 35 36 37 38 ]);
M_.block_structure.block(3).g1_sparse_rowval = int32([]);
M_.block_structure.block(3).g1_sparse_colval = int32([]);
M_.block_structure.block(3).g1_sparse_colptr = int32([]);
M_.block_structure.variable_reordered = [ 10 8 5 9 11 7 2 6 1 3 12 4 13];
M_.block_structure.equation_reordered = [ 13 3 1 8 2 4 10 12 5 7 9 11 6];
M_.block_structure.incidence(1).lead_lag = -1;
M_.block_structure.incidence(1).sparse_IM = [
 4 7;
 5 2;
 6 11;
 7 2;
 9 11;
 12 6;
 13 10;
];
M_.block_structure.incidence(2).lead_lag = 0;
M_.block_structure.incidence(2).sparse_IM = [
 1 4;
 1 5;
 1 10;
 2 2;
 2 7;
 2 8;
 2 11;
 3 2;
 3 8;
 3 9;
 4 4;
 4 5;
 4 7;
 5 1;
 5 2;
 6 11;
 6 13;
 7 2;
 7 3;
 8 3;
 8 9;
 9 11;
 9 12;
 10 2;
 10 7;
 10 10;
 10 12;
 11 4;
 11 6;
 12 1;
 12 4;
 12 6;
 13 10;
];
M_.block_structure.incidence(3).lead_lag = 1;
M_.block_structure.incidence(3).sparse_IM = [
 8 3;
 10 12;
 11 1;
 11 4;
];
M_.block_structure.dyn_tmp_nbr = 0;
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
[~, ~, M_.state_var] = set_state_space(struct(), M_);
oo_.steady_state = zeros(13, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(1, 1);
M_.params = NaN(15, 1);
M_.endo_trends = struct('deflator', cell(13, 1), 'log_deflator', cell(13, 1), 'growth_factor', cell(13, 1), 'log_growth_factor', cell(13, 1));
M_.dynamic_g1_sparse_rowval = int32([5 7 12 4 13 6 9 5 12 2 3 5 7 10 7 8 1 4 11 12 1 4 11 12 2 4 10 2 3 3 8 1 10 13 2 6 9 9 10 6 11 8 11 10 13 ]);
M_.dynamic_g1_sparse_colval = int32([2 2 6 7 10 11 11 14 14 15 15 15 15 15 16 16 17 17 17 17 18 18 19 19 20 20 20 21 21 22 22 23 23 23 24 24 24 25 25 26 27 29 30 38 40 ]);
M_.dynamic_g1_sparse_colptr = int32([1 1 3 3 3 3 4 5 5 5 6 8 8 8 10 15 17 21 23 25 28 30 32 35 38 40 41 42 42 43 44 44 44 44 44 44 44 44 45 45 46 ]);
M_.dynamic_g2_sparse_indices = int32([]);
M_.lhs = {
'gdp'; 
'rmc_D'; 
'nmc_D'; 
'rwage'; 
'infl'; 
'infl_U'; 
'cpi'; 
'resetprice_D'; 
'cpi_U'; 
'resetprice_U'; 
'gdp'; 
'nomint'; 
'tot'; 
};
M_.dynamic_mcp_equations_reordering = [1; 2; 3; 4; 5; 6; 7; 8; 9; 10; 11; 12; 13; ];
M_.static_tmp_nbr = [0; 0; 0; 0; ];
M_.block_structure_stat.block(1).Simulation_Type = 1;
M_.block_structure_stat.block(1).endo_nbr = 2;
M_.block_structure_stat.block(1).mfs = 2;
M_.block_structure_stat.block(1).equation = [ 5 6];
M_.block_structure_stat.block(1).variable = [ 1 13];
M_.block_structure_stat.block(2).Simulation_Type = 3;
M_.block_structure_stat.block(2).endo_nbr = 1;
M_.block_structure_stat.block(2).mfs = 1;
M_.block_structure_stat.block(2).equation = [ 13];
M_.block_structure_stat.block(2).variable = [ 10];
M_.block_structure_stat.block(3).Simulation_Type = 6;
M_.block_structure_stat.block(3).endo_nbr = 2;
M_.block_structure_stat.block(3).mfs = 2;
M_.block_structure_stat.block(3).equation = [ 11 12];
M_.block_structure_stat.block(3).variable = [ 6 4];
M_.block_structure_stat.block(4).Simulation_Type = 3;
M_.block_structure_stat.block(4).endo_nbr = 1;
M_.block_structure_stat.block(4).mfs = 1;
M_.block_structure_stat.block(4).equation = [ 1];
M_.block_structure_stat.block(4).variable = [ 5];
M_.block_structure_stat.block(5).Simulation_Type = 3;
M_.block_structure_stat.block(5).endo_nbr = 1;
M_.block_structure_stat.block(5).mfs = 1;
M_.block_structure_stat.block(5).equation = [ 4];
M_.block_structure_stat.block(5).variable = [ 7];
M_.block_structure_stat.block(6).Simulation_Type = 6;
M_.block_structure_stat.block(6).endo_nbr = 6;
M_.block_structure_stat.block(6).mfs = 6;
M_.block_structure_stat.block(6).equation = [ 2 7 8 9 10 3];
M_.block_structure_stat.block(6).variable = [ 8 3 9 11 12 2];
M_.block_structure_stat.variable_reordered = [ 1 13 10 6 4 5 7 8 3 9 11 12 2];
M_.block_structure_stat.equation_reordered = [ 5 6 13 11 12 1 4 2 7 8 9 10 3];
M_.block_structure_stat.incidence.sparse_IM = [
 1 4;
 1 5;
 1 10;
 2 2;
 2 7;
 2 8;
 2 11;
 3 2;
 3 8;
 3 9;
 4 4;
 4 5;
 4 7;
 5 1;
 6 13;
 7 2;
 7 3;
 8 3;
 8 9;
 9 11;
 9 12;
 10 2;
 10 7;
 10 10;
 10 12;
 11 1;
 11 6;
 12 1;
 12 4;
 12 6;
 13 10;
];
M_.block_structure_stat.tmp_nbr = 0;
M_.block_structure_stat.block(1).g1_sparse_rowval = int32([]);
M_.block_structure_stat.block(1).g1_sparse_colval = int32([]);
M_.block_structure_stat.block(1).g1_sparse_colptr = int32([]);
M_.block_structure_stat.block(2).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(2).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(2).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(3).g1_sparse_rowval = int32([1 2 2 ]);
M_.block_structure_stat.block(3).g1_sparse_colval = int32([1 1 2 ]);
M_.block_structure_stat.block(3).g1_sparse_colptr = int32([1 3 4 ]);
M_.block_structure_stat.block(4).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(4).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(4).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(5).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(5).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(5).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(6).g1_sparse_rowval = int32([1 6 2 3 3 6 1 4 4 5 1 2 5 6 ]);
M_.block_structure_stat.block(6).g1_sparse_colval = int32([1 1 2 2 3 3 4 4 5 5 6 6 6 6 ]);
M_.block_structure_stat.block(6).g1_sparse_colptr = int32([1 3 5 7 9 11 15 ]);
M_.static_g1_sparse_rowval = int32([5 11 12 2 3 7 10 7 8 1 4 12 1 4 11 12 2 4 10 2 3 3 8 1 10 13 2 9 9 10 6 ]);
M_.static_g1_sparse_colval = int32([1 1 1 2 2 2 2 3 3 4 4 4 5 5 6 6 7 7 7 8 8 9 9 10 10 10 11 11 12 12 13 ]);
M_.static_g1_sparse_colptr = int32([1 4 8 10 13 15 17 20 22 24 27 29 31 32 ]);
M_.static_mcp_equations_reordering = [1; 2; 3; 4; 5; 6; 7; 8; 9; 10; 11; 12; 13; ];
M_.params(1) = 0.375;
alph = M_.params(1);
rbar    = 2;        
M_.params(10) = 0.5;
intsub = M_.params(10);
M_.params(11) = 3;
frisch = M_.params(11);
M_.params(3) = 0.9166666666666666;
theta_D = M_.params(3);
M_.params(4) = 0.75;
theta_U = M_.params(4);
M_.params(5) = 0.4;
alph_D = M_.params(5);
M_.params(8) = 0.5;
mf = M_.params(8);
M_.params(9) = 0.8879040017426006;
psi_w = M_.params(9);
M_.params(12) = 0.9;
phi = M_.params(12);
M_.params(13) = 3;
chipi = M_.params(13);
M_.params(14) = 0.5;
chiy = M_.params(14);
M_.params(15) = 0.8;
rho = M_.params(15);
M_.params(2) = (1/(1+rbar/100))^0.08333333333333333;
bet = M_.params(2);
M_.params(6) = 11;
epsil = M_.params(6);
M_.params(7) = M_.params(5)*M_.params(6)/(M_.params(6)-1)/(M_.params(5)*M_.params(6)/(M_.params(6)-1)+1-M_.params(5));
Phi_DU = M_.params(7);
%
% SHOCKS instructions
%
M_.Sigma_e(1, 1) = (100)^2;
options_.irf = 48;
options_.order = 1;
var_list_ = {'infl';'infl_U';'gdp';'tot';'nomint';'rwage';'rmc_D'};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);
T = 48;
months = 1:T;
infl_irf = oo_.irfs.infl_totsh;
tot_irf  = oo_.irfs.tot_totsh;
infl_norm = infl_irf / infl_irf(1);
tot_norm  = tot_irf  / tot_irf(1);
figure;
plot(months, tot_norm,  'k-.', 'LineWidth', 2.0); hold on;
plot(months, infl_norm, 'b-',  'LineWidth', 2.0);
yline(0, 'Color', [0.6 0.6 0.6], 'LineWidth', 0.8);
xlabel('Months after shock');
ylabel('Fraction of period-1 value remaining');
title('Inflation persistence vs energy price shock decay');
legend('Terms of trade (tot)', 'CPI inflation (infl)', 'Location', 'northeast');
grid on;


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'inflation_network_realwage_fix_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'inflation_network_realwage_fix_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'inflation_network_realwage_fix_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'inflation_network_realwage_fix_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'inflation_network_realwage_fix_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'inflation_network_realwage_fix_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'inflation_network_realwage_fix_results.mat'], 'oo_recursive_', '-append');
end
if exist('options_mom_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'inflation_network_realwage_fix_results.mat'], 'options_mom_', '-append');
end
disp('Note: 1 warning(s) encountered in the preprocessor')
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
