%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clearvars -global
clear_persistent_variables(fileparts(which('dynare')), false)
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info
options_ = [];
M_.fname = 'inflation_searchmatch';
M_.dynare_version = '7.0';
oo_.dynare_version = '7.0';
options_.dynare_version = '7.0';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(1,1);
M_.exo_names_tex = cell(1,1);
M_.exo_names_long = cell(1,1);
M_.exo_names(1) = {'totsh'};
M_.exo_names_tex(1) = {'totsh'};
M_.exo_names_long(1) = {'totsh'};
M_.endo_names = cell(16,1);
M_.endo_names_tex = cell(16,1);
M_.endo_names_long = cell(16,1);
M_.endo_names(1) = {'infl'};
M_.endo_names_tex(1) = {'infl'};
M_.endo_names_long(1) = {'infl'};
M_.endo_names(2) = {'cpi'};
M_.endo_names_tex(2) = {'cpi'};
M_.endo_names_long(2) = {'cpi'};
M_.endo_names(3) = {'resetprice'};
M_.endo_names_tex(3) = {'resetprice'};
M_.endo_names_long(3) = {'resetprice'};
M_.endo_names(4) = {'gdp'};
M_.endo_names_tex(4) = {'gdp'};
M_.endo_names_long(4) = {'gdp'};
M_.endo_names(5) = {'cons'};
M_.endo_names_tex(5) = {'cons'};
M_.endo_names_long(5) = {'cons'};
M_.endo_names(6) = {'n'};
M_.endo_names_tex(6) = {'n'};
M_.endo_names_long(6) = {'n'};
M_.endo_names(7) = {'u'};
M_.endo_names_tex(7) = {'u'};
M_.endo_names_long(7) = {'u'};
M_.endo_names(8) = {'v'};
M_.endo_names_tex(8) = {'v'};
M_.endo_names_long(8) = {'v'};
M_.endo_names(9) = {'tightness'};
M_.endo_names_tex(9) = {'tightness'};
M_.endo_names_long(9) = {'tightness'};
M_.endo_names(10) = {'qrate'};
M_.endo_names_tex(10) = {'qrate'};
M_.endo_names_long(10) = {'qrate'};
M_.endo_names(11) = {'rwage'};
M_.endo_names_tex(11) = {'rwage'};
M_.endo_names_long(11) = {'rwage'};
M_.endo_names(12) = {'wnash'};
M_.endo_names_tex(12) = {'wnash'};
M_.endo_names_long(12) = {'wnash'};
M_.endo_names(13) = {'rmc'};
M_.endo_names_tex(13) = {'rmc'};
M_.endo_names_long(13) = {'rmc'};
M_.endo_names(14) = {'nmc'};
M_.endo_names_tex(14) = {'nmc'};
M_.endo_names_long(14) = {'nmc'};
M_.endo_names(15) = {'nomint'};
M_.endo_names_tex(15) = {'nomint'};
M_.endo_names_long(15) = {'nomint'};
M_.endo_names(16) = {'tot'};
M_.endo_names_tex(16) = {'tot'};
M_.endo_names_long(16) = {'tot'};
M_.endo_partitions = struct();
M_.param_names = cell(14,1);
M_.param_names_tex = cell(14,1);
M_.param_names_long = cell(14,1);
M_.param_names(1) = {'alph'};
M_.param_names_tex(1) = {'alph'};
M_.param_names_long(1) = {'alph'};
M_.param_names(2) = {'bet'};
M_.param_names_tex(2) = {'bet'};
M_.param_names_long(2) = {'bet'};
M_.param_names(3) = {'thetap'};
M_.param_names_tex(3) = {'thetap'};
M_.param_names_long(3) = {'thetap'};
M_.param_names(4) = {'gamma'};
M_.param_names_tex(4) = {'gamma'};
M_.param_names_long(4) = {'gamma'};
M_.param_names(5) = {'sigm'};
M_.param_names_tex(5) = {'sigm'};
M_.param_names_long(5) = {'sigm'};
M_.param_names(6) = {'rhon'};
M_.param_names_tex(6) = {'rhon'};
M_.param_names_long(6) = {'rhon'};
M_.param_names(7) = {'nbar'};
M_.param_names_tex(7) = {'nbar'};
M_.param_names_long(7) = {'nbar'};
M_.param_names(8) = {'ubar'};
M_.param_names_tex(8) = {'ubar'};
M_.param_names_long(8) = {'ubar'};
M_.param_names(9) = {'cvratio'};
M_.param_names_tex(9) = {'cvratio'};
M_.param_names_long(9) = {'cvratio'};
M_.param_names(10) = {'intsub'};
M_.param_names_tex(10) = {'intsub'};
M_.param_names_long(10) = {'intsub'};
M_.param_names(11) = {'phi'};
M_.param_names_tex(11) = {'phi'};
M_.param_names_long(11) = {'phi'};
M_.param_names(12) = {'chipi'};
M_.param_names_tex(12) = {'chipi'};
M_.param_names_long(12) = {'chipi'};
M_.param_names(13) = {'chiy'};
M_.param_names_tex(13) = {'chiy'};
M_.param_names_long(13) = {'chiy'};
M_.param_names(14) = {'rho'};
M_.param_names_tex(14) = {'rho'};
M_.param_names_long(14) = {'rho'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 1;
M_.endo_nbr = 16;
M_.param_nbr = 14;
M_.orig_endo_nbr = 16;
M_.aux_vars = [];
M_.heterogeneity_aggregates = {
};
M_.database = {};
M_.Sigma_e = zeros(1, 1);
M_.Correlation_matrix = eye(1, 1);
M_.Skew_e = zeros(0, 4);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = struct([]);
M_.surprise_shocks = struct([]);
M_.learnt_shocks = struct([]);
M_.learnt_endval = struct([]);
M_.shock_paths = struct([]);
M_.heteroskedastic_shocks.Qvalue_orig = struct([]);
M_.heteroskedastic_shocks.Qscale_orig = struct([]);
M_.matched_irfs = {};
M_.matched_irfs_weights = {};
M_.perfect_foresight_controlled_paths = struct([]);
options_.linear = true;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
options_.ramsey_policy = false;
options_.discretionary_policy = false;
M_.nonzero_hessian_eqs = [];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.eq_nbr = 16;
M_.ramsey_orig_eq_nbr = 0;
M_.ramsey_orig_endo_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 1;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 1;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 1;
M_.lead_lag_incidence = [
 0 5 21;
 1 6 0;
 0 7 22;
 0 8 0;
 0 9 23;
 2 10 0;
 0 11 0;
 0 12 0;
 0 13 24;
 0 14 0;
 0 15 0;
 0 16 0;
 0 17 0;
 0 18 0;
 3 19 0;
 4 20 0;]';
M_.nstatic = 8;
M_.nfwrd   = 4;
M_.npred   = 4;
M_.nboth   = 0;
M_.nsfwrd   = 4;
M_.nspred   = 4;
M_.ndynamic   = 8;
M_.dynamic_tmp_nbr = [0; 0; 0; 0; ];
M_.equations_tags = {
  1 , 'name' , 'rmc' ;
  2 , 'name' , 'nmc' ;
  3 , 'name' , 'infl' ;
  4 , 'name' , 'cpi' ;
  5 , 'name' , 'resetprice' ;
  6 , 'name' , 'nomint' ;
  7 , 'name' , 'cons' ;
  8 , 'name' , 'gdp' ;
  9 , 'name' , 'tot' ;
  10 , 'name' , 'u' ;
  11 , 'name' , 'qrate' ;
  12 , 'name' , 'v' ;
  13 , 'name' , 'n' ;
  14 , 'name' , '14' ;
  15 , 'name' , 'wnash' ;
  16 , 'name' , 'rwage' ;
};
M_.mapping.infl.eqidx = [3 6 7 ];
M_.mapping.cpi.eqidx = [2 3 4 ];
M_.mapping.resetprice.eqidx = [4 5 ];
M_.mapping.gdp.eqidx = [6 8 ];
M_.mapping.cons.eqidx = [7 8 ];
M_.mapping.n.eqidx = [10 13 ];
M_.mapping.u.eqidx = [10 12 ];
M_.mapping.v.eqidx = [8 12 13 ];
M_.mapping.tightness.eqidx = [11 12 14 15 ];
M_.mapping.qrate.eqidx = [11 13 ];
M_.mapping.rwage.eqidx = [1 14 16 ];
M_.mapping.wnash.eqidx = [15 16 ];
M_.mapping.rmc.eqidx = [1 2 14 15 ];
M_.mapping.nmc.eqidx = [2 5 ];
M_.mapping.nomint.eqidx = [6 7 ];
M_.mapping.tot.eqidx = [1 9 ];
M_.mapping.totsh.eqidx = [9 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.block_structure.time_recursive = false;
M_.block_structure.block(1).Simulation_Type = 1;
M_.block_structure.block(1).endo_nbr = 1;
M_.block_structure.block(1).mfs = 1;
M_.block_structure.block(1).equation = [ 9];
M_.block_structure.block(1).variable = [ 16];
M_.block_structure.block(1).is_linear = true;
M_.block_structure.block(1).bytecode_jacob_cols_to_sparse = [1 2 ];
M_.block_structure.block(2).Simulation_Type = 7;
M_.block_structure.block(2).endo_nbr = 4;
M_.block_structure.block(2).mfs = 3;
M_.block_structure.block(2).equation = [ 1 14 16 15];
M_.block_structure.block(2).variable = [ 13 11 12 9];
M_.block_structure.block(2).is_linear = true;
M_.block_structure.block(2).bytecode_jacob_cols_to_sparse = [0 1 2 3 0 ];
M_.block_structure.block(3).Simulation_Type = 1;
M_.block_structure.block(3).endo_nbr = 1;
M_.block_structure.block(3).mfs = 0;
M_.block_structure.block(3).equation = [ 11];
M_.block_structure.block(3).variable = [ 10];
M_.block_structure.block(3).is_linear = true;
M_.block_structure.block(3).bytecode_jacob_cols_to_sparse = [0 ];
M_.block_structure.block(4).Simulation_Type = 6;
M_.block_structure.block(4).endo_nbr = 3;
M_.block_structure.block(4).mfs = 2;
M_.block_structure.block(4).equation = [ 12 10 13];
M_.block_structure.block(4).variable = [ 8 7 6];
M_.block_structure.block(4).is_linear = true;
M_.block_structure.block(4).bytecode_jacob_cols_to_sparse = [0 0 1 2 ];
M_.block_structure.block(5).Simulation_Type = 8;
M_.block_structure.block(5).endo_nbr = 3;
M_.block_structure.block(5).mfs = 3;
M_.block_structure.block(5).equation = [ 5 2 4];
M_.block_structure.block(5).variable = [ 14 2 3];
M_.block_structure.block(5).is_linear = true;
M_.block_structure.block(5).bytecode_jacob_cols_to_sparse = [2 4 5 6 9 ];
M_.block_structure.block(6).Simulation_Type = 1;
M_.block_structure.block(6).endo_nbr = 1;
M_.block_structure.block(6).mfs = 0;
M_.block_structure.block(6).equation = [ 3];
M_.block_structure.block(6).variable = [ 1];
M_.block_structure.block(6).is_linear = true;
M_.block_structure.block(6).bytecode_jacob_cols_to_sparse = [0 ];
M_.block_structure.block(7).Simulation_Type = 8;
M_.block_structure.block(7).endo_nbr = 3;
M_.block_structure.block(7).mfs = 2;
M_.block_structure.block(7).equation = [ 8 6 7];
M_.block_structure.block(7).variable = [ 4 15 5];
M_.block_structure.block(7).is_linear = true;
M_.block_structure.block(7).bytecode_jacob_cols_to_sparse = [1 0 3 4 6 ];
M_.block_structure.block(1).g1_sparse_rowval = int32([]);
M_.block_structure.block(1).g1_sparse_colval = int32([]);
M_.block_structure.block(1).g1_sparse_colptr = int32([]);
M_.block_structure.block(2).g1_sparse_rowval = int32([2 3 2 3 1 3 ]);
M_.block_structure.block(2).g1_sparse_colval = int32([1 1 2 2 3 3 ]);
M_.block_structure.block(2).g1_sparse_colptr = int32([1 3 5 7 ]);
M_.block_structure.block(3).g1_sparse_rowval = int32([]);
M_.block_structure.block(3).g1_sparse_colval = int32([]);
M_.block_structure.block(3).g1_sparse_colptr = int32([]);
M_.block_structure.block(4).g1_sparse_rowval = int32([1 2 2 ]);
M_.block_structure.block(4).g1_sparse_colval = int32([1 1 2 ]);
M_.block_structure.block(4).g1_sparse_colptr = int32([1 3 4 ]);
M_.block_structure.block(5).g1_sparse_rowval = int32([3 1 2 2 3 1 3 1 ]);
M_.block_structure.block(5).g1_sparse_colval = int32([2 4 4 5 5 6 6 9 ]);
M_.block_structure.block(5).g1_sparse_colptr = int32([1 1 2 2 4 6 8 8 8 9 ]);
M_.block_structure.block(6).g1_sparse_rowval = int32([]);
M_.block_structure.block(6).g1_sparse_colval = int32([]);
M_.block_structure.block(6).g1_sparse_colptr = int32([]);
M_.block_structure.block(7).g1_sparse_rowval = int32([1 1 2 1 2 2 ]);
M_.block_structure.block(7).g1_sparse_colval = int32([1 3 3 4 4 6 ]);
M_.block_structure.block(7).g1_sparse_colptr = int32([1 2 2 4 6 6 7 ]);
M_.block_structure.variable_reordered = [ 16 13 11 12 9 10 8 7 6 14 2 3 1 4 15 5];
M_.block_structure.equation_reordered = [ 9 1 14 16 15 11 12 10 13 5 2 4 3 8 6 7];
M_.block_structure.incidence(1).lead_lag = -1;
M_.block_structure.incidence(1).sparse_IM = [
 3 2;
 4 2;
 6 15;
 9 16;
 10 6;
 13 6;
];
M_.block_structure.incidence(2).lead_lag = 0;
M_.block_structure.incidence(2).sparse_IM = [
 1 11;
 1 13;
 1 16;
 2 2;
 2 13;
 2 14;
 3 1;
 3 2;
 4 2;
 4 3;
 5 3;
 5 14;
 6 1;
 6 4;
 6 15;
 7 5;
 7 15;
 8 4;
 8 5;
 8 8;
 9 16;
 10 7;
 11 9;
 11 10;
 12 7;
 12 8;
 12 9;
 13 6;
 13 8;
 13 10;
 14 9;
 14 11;
 14 13;
 15 9;
 15 12;
 15 13;
 16 11;
 16 12;
];
M_.block_structure.incidence(3).lead_lag = 1;
M_.block_structure.incidence(3).sparse_IM = [
 5 3;
 7 1;
 7 5;
 14 9;
];
M_.block_structure.dyn_tmp_nbr = 0;
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
[~, ~, M_.state_var] = set_state_space(struct(), M_);
oo_.steady_state = zeros(16, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(1, 1);
M_.params = NaN(14, 1);
M_.endo_trends = struct('deflator', cell(16, 1), 'log_deflator', cell(16, 1), 'growth_factor', cell(16, 1), 'log_growth_factor', cell(16, 1));
M_.dynamic_g1_sparse_rowval = int32([3 4 10 13 6 9 3 6 2 3 4 4 5 6 8 7 8 13 10 12 8 12 13 11 12 14 15 11 13 1 14 16 15 16 1 2 14 15 2 5 6 7 1 9 7 5 7 14 9 ]);
M_.dynamic_g1_sparse_colval = int32([2 2 6 6 15 16 17 17 18 18 18 19 19 20 20 21 21 22 23 23 24 24 24 25 25 25 25 26 26 27 27 27 28 28 29 29 29 29 30 30 31 31 32 32 33 35 37 41 49 ]);
M_.dynamic_g1_sparse_colptr = int32([1 1 3 3 3 3 5 5 5 5 5 5 5 5 5 6 7 9 12 14 16 18 19 21 24 28 30 33 35 39 41 43 45 46 46 47 47 48 48 48 48 49 49 49 49 49 49 49 49 50 ]);
M_.dynamic_g2_sparse_indices = int32([]);
M_.lhs = {
'rmc'; 
'nmc'; 
'infl'; 
'cpi'; 
'resetprice'; 
'nomint'; 
'cons'; 
'gdp'; 
'tot'; 
'u'; 
'qrate'; 
'v'; 
'n'; 
'sigm*tightness'; 
'wnash'; 
'rwage'; 
};
M_.dynamic_mcp_equations_reordering = [1; 2; 3; 4; 5; 6; 7; 8; 9; 10; 11; 12; 13; 14; 15; 16; ];
M_.static_tmp_nbr = [0; 0; 0; 0; ];
M_.block_structure_stat.block(1).Simulation_Type = 1;
M_.block_structure_stat.block(1).endo_nbr = 1;
M_.block_structure_stat.block(1).mfs = 1;
M_.block_structure_stat.block(1).equation = [ 3];
M_.block_structure_stat.block(1).variable = [ 1];
M_.block_structure_stat.block(2).Simulation_Type = 3;
M_.block_structure_stat.block(2).endo_nbr = 1;
M_.block_structure_stat.block(2).mfs = 1;
M_.block_structure_stat.block(2).equation = [ 9];
M_.block_structure_stat.block(2).variable = [ 16];
M_.block_structure_stat.block(3).Simulation_Type = 6;
M_.block_structure_stat.block(3).endo_nbr = 4;
M_.block_structure_stat.block(3).mfs = 4;
M_.block_structure_stat.block(3).equation = [ 1 14 15 16];
M_.block_structure_stat.block(3).variable = [ 13 9 12 11];
M_.block_structure_stat.block(4).Simulation_Type = 1;
M_.block_structure_stat.block(4).endo_nbr = 1;
M_.block_structure_stat.block(4).mfs = 1;
M_.block_structure_stat.block(4).equation = [ 11];
M_.block_structure_stat.block(4).variable = [ 10];
M_.block_structure_stat.block(5).Simulation_Type = 6;
M_.block_structure_stat.block(5).endo_nbr = 3;
M_.block_structure_stat.block(5).mfs = 3;
M_.block_structure_stat.block(5).equation = [ 10 12 13];
M_.block_structure_stat.block(5).variable = [ 6 7 8];
M_.block_structure_stat.block(6).Simulation_Type = 6;
M_.block_structure_stat.block(6).endo_nbr = 3;
M_.block_structure_stat.block(6).mfs = 3;
M_.block_structure_stat.block(6).equation = [ 6 7 8];
M_.block_structure_stat.block(6).variable = [ 4 15 5];
M_.block_structure_stat.block(7).Simulation_Type = 6;
M_.block_structure_stat.block(7).endo_nbr = 3;
M_.block_structure_stat.block(7).mfs = 3;
M_.block_structure_stat.block(7).equation = [ 4 5 2];
M_.block_structure_stat.block(7).variable = [ 2 3 14];
M_.block_structure_stat.variable_reordered = [ 1 16 13 9 12 11 10 6 7 8 4 15 5 2 3 14];
M_.block_structure_stat.equation_reordered = [ 3 9 1 14 15 16 11 10 12 13 6 7 8 4 5 2];
M_.block_structure_stat.incidence.sparse_IM = [
 1 11;
 1 13;
 1 16;
 2 2;
 2 13;
 2 14;
 3 1;
 4 2;
 4 3;
 5 3;
 5 14;
 6 1;
 6 4;
 6 15;
 7 1;
 7 15;
 8 4;
 8 5;
 8 8;
 9 16;
 10 6;
 10 7;
 11 9;
 11 10;
 12 7;
 12 8;
 12 9;
 13 6;
 13 8;
 13 10;
 14 9;
 14 11;
 14 13;
 15 9;
 15 12;
 15 13;
 16 11;
 16 12;
];
M_.block_structure_stat.tmp_nbr = 0;
M_.block_structure_stat.block(1).g1_sparse_rowval = int32([]);
M_.block_structure_stat.block(1).g1_sparse_colval = int32([]);
M_.block_structure_stat.block(1).g1_sparse_colptr = int32([]);
M_.block_structure_stat.block(2).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(2).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(2).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(3).g1_sparse_rowval = int32([1 2 3 2 3 3 4 1 2 4 ]);
M_.block_structure_stat.block(3).g1_sparse_colval = int32([1 1 1 2 2 3 3 4 4 4 ]);
M_.block_structure_stat.block(3).g1_sparse_colptr = int32([1 4 6 8 11 ]);
M_.block_structure_stat.block(4).g1_sparse_rowval = int32([]);
M_.block_structure_stat.block(4).g1_sparse_colval = int32([]);
M_.block_structure_stat.block(4).g1_sparse_colptr = int32([]);
M_.block_structure_stat.block(5).g1_sparse_rowval = int32([1 3 1 2 2 3 ]);
M_.block_structure_stat.block(5).g1_sparse_colval = int32([1 1 2 2 3 3 ]);
M_.block_structure_stat.block(5).g1_sparse_colptr = int32([1 3 5 7 ]);
M_.block_structure_stat.block(6).g1_sparse_rowval = int32([1 3 1 2 3 ]);
M_.block_structure_stat.block(6).g1_sparse_colval = int32([1 1 2 2 3 ]);
M_.block_structure_stat.block(6).g1_sparse_colptr = int32([1 3 5 6 ]);
M_.block_structure_stat.block(7).g1_sparse_rowval = int32([1 3 1 2 2 3 ]);
M_.block_structure_stat.block(7).g1_sparse_colval = int32([1 1 2 2 3 3 ]);
M_.block_structure_stat.block(7).g1_sparse_colptr = int32([1 3 5 7 ]);
M_.static_g1_sparse_rowval = int32([3 6 7 2 4 4 5 6 8 8 10 13 10 12 8 12 13 11 12 14 15 11 13 1 14 16 15 16 1 2 14 15 2 5 6 7 1 9 ]);
M_.static_g1_sparse_colval = int32([1 1 1 2 2 3 3 4 4 5 6 6 7 7 8 8 8 9 9 9 9 10 10 11 11 11 12 12 13 13 13 13 14 14 15 15 16 16 ]);
M_.static_g1_sparse_colptr = int32([1 4 6 8 10 11 13 15 18 22 24 27 29 33 35 37 39 ]);
M_.static_mcp_equations_reordering = [1; 2; 3; 4; 5; 6; 7; 8; 9; 10; 11; 12; 13; 14; 15; 16; ];
M_.params(1) = 0.15;
alph = M_.params(1);
rbar    = 2;      
M_.params(10) = 0.5;
intsub = M_.params(10);
M_.params(3) = 0.9166666666666666;
thetap = M_.params(3);
M_.params(11) = 0.9;
phi = M_.params(11);
M_.params(12) = 3;
chipi = M_.params(12);
M_.params(13) = 0.5;
chiy = M_.params(13);
M_.params(14) = 0.99;
rho = M_.params(14);
M_.params(4) = 0.705;
gamma = M_.params(4);
M_.params(5) = 0.5;
sigm = M_.params(5);
M_.params(6) = 0.96;
rhon = M_.params(6);
M_.params(7) = 0.95;
nbar = M_.params(7);
M_.params(8) = 0.05;
ubar = M_.params(8);
M_.params(9) = 0.01;
cvratio = M_.params(9);
M_.params(2) = (1/(1+rbar/100))^0.08333333333333333;
bet = M_.params(2);
%
% SHOCKS instructions
%
M_.Sigma_e(1, 1) = (100)^2;
options_.irf = 24;
options_.order = 1;
var_list_ = {'infl';'gdp';'cons';'tot';'nomint';'u';'tightness';'rwage'};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);
infl_irf = oo_.irfs.infl_totsh;
tot_irf  = oo_.irfs.tot_totsh;
periods  = 1:24;
infl_norm = infl_irf / infl_irf(1);   
tot_norm  = tot_irf  / tot_irf(1);    
figure('Name', 'Inflation vs ToT: Normalised IRFs and Ratio');
subplot(2,1,1);
plot(periods, infl_norm, 'b-',  'LineWidth', 2); hold on;
plot(periods, tot_norm,  'r--', 'LineWidth', 2);
yline(0, 'k-');
legend('infl (normalised)', 'tot (normalised)', 'Location', 'NorthEast');
title('Normalised IRFs: Inflation vs Terms of Trade');
xlabel('Months'); ylabel('Relative to period-1 value');
subplot(2,1,2);
ratio = infl_norm ./ tot_norm;
plot(periods, ratio, 'k-', 'LineWidth', 2);
yline(1, 'r--');   
xlabel('Months'); ylabel('infl / tot (normalised)');
title('Ratio of normalised inflation to normalised tot');


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'inflation_searchmatch_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'inflation_searchmatch_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'inflation_searchmatch_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'inflation_searchmatch_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'inflation_searchmatch_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'inflation_searchmatch_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'inflation_searchmatch_results.mat'], 'oo_recursive_', '-append');
end
if exist('options_mom_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'inflation_searchmatch_results.mat'], 'options_mom_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
